before_install:
  - gem update --system 2.1.11
language: ruby
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "rbx"
  - "jruby"
matrix:
  allow_failures:
    - rvm: "rbx"
    - rvm: "jruby"
